
// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.EntityFrameworkCore;
using Proyecto.Datos.Contexto.Repositorio;

namespace Proyecto.Datos.Contexto
{
    public partial class ContextoProyecto : DbContext
    {
        public ContextoProyecto()
        {
        }

        public ContextoProyecto(DbContextOptions<ContextoProyecto> options)
            : base(options)
        {
        }

        public virtual DbSet<Usuario> Usuario { get; set; } 
        public virtual DbSet<Pais> Pais { get; set; } 
        public virtual DbSet<Departamento> Departamento { get; set; } 
        public virtual DbSet<Municipio> Municipio { get; set; } 
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Usuario>(entity =>
            {
                entity.ToTable("Usuario", "aplicacion");

                entity.HasKey(e => e.id);
                entity.Property(e => e.id).ValueGeneratedNever();
             });

            modelBuilder.Entity<Pais>(entity =>
            {
                entity.ToTable("Pais", "parametricas");
                entity.HasKey(e => e.id);
                entity.Property(e => e.id).ValueGeneratedNever();
            });

            modelBuilder.Entity<Departamento>(entity =>
            {
                entity.ToTable("Departamento", "parametricas");
                entity.HasKey(e => e.id);
                entity.Property(e => e.id).ValueGeneratedNever();
            });

            modelBuilder.Entity<Municipio>(entity =>
            {
                entity.ToTable("Municipio", "parametricas");
                entity.HasKey(e => e.id);
                entity.Property(e => e.id).ValueGeneratedNever();

            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}
